name: 'Release Canary'

on:
  issue_comment:
    types: [ created ]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read # for checkout
  pull-requests: write  # for comments
  packages: write # for publish

jobs:
  start:
    name: Start publishing
    runs-on: ubuntu-latest
    if: |
      (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'CONTRIBUTOR') &&
      startsWith(github.event.comment.body, '/canary-release')
    steps:
      - name: complete
        run: gh pr comment -b "ðŸŽ‰ Canary Release build started" ${{github.event.issue.number}} -R ${{ github.repository }}
        
  canary-npm:
    name: Publish Canary to NPM
    runs-on: ubuntu-latest
    needs: start
    if: |
      (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'CONTRIBUTOR') &&
      startsWith(github.event.comment.body, '/canary-release')
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ fromJSON(steps.pr.outputs.result).head.ref }}
          repository: ${{ fromJSON(steps.pr.outputs.result).head.repo.full_name }}
          fetch-depth: 0
      
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Setup Node ${{ steps.nvm.outputs.NVMRC }}
        uses: actions/setup-node@v2
        with:
          node-version:  ${{ steps.nvm.outputs.NVMRC }}
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install
        run: npm ci

      - name: Authenticate with NPM Registry
        run: |
          echo "@serveside:registry=http://registry.npmjs.org/" > .npmrc
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        run: npm run release:canary:ci
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  canary-gh:
    name: Publish Canary to GH
    runs-on: ubuntu-latest
    needs: start
    if: |
      (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'CONTRIBUTOR') &&
      startsWith(github.event.comment.body, '/canary-release')
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ fromJSON(steps.pr.outputs.result).head.ref }}
          repository: ${{ fromJSON(steps.pr.outputs.result).head.repo.full_name }}
          fetch-depth: 0
      
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Setup Node ${{ steps.nvm.outputs.NVMRC }}
        uses: actions/setup-node@v2
        with:
          node-version:  ${{ steps.nvm.outputs.NVMRC }}
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install
        run: npm ci

      - name: Authenticate with GH Registry
        run: |
          echo "@serveside:registry=https://npm.pkg.github.com/" > .npmrc
          echo "registry=https://npm.pkg.github.com/" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GH
        run: npm run release:canary:ci
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-complete:
    name: Publishing Complete
    needs: 
      - canary-gh
      - canary-npm
    runs-on: ubuntu-latest
    steps:
      - name: complete
        run: gh pr comment -b "ðŸŽ‰ Canary Release complete!" ${{github.event.issue.number}} -R ${{ github.repository }}
      - name: failure
        if: ${{ failure() || cancelled() }}
        run: gh pr comment -b "Some error happened on publish. Please check the action logs" ${{github.event.issue.number}} -R ${{ github.repository }}