# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Configure CI Git User
        run: |
          git config --global user.name '@maniator'
          git config --global user.email 'maniator@users.noreply.github.com'
          git remote set-url origin https://$GITHUB_ACTOR:$GH_TOKEN@github.com/serveside/ssr-aas
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Checkout release branch
        run: git checkout -b $GITHUB_SHA-release && git push --set-upstream origin $GITHUB_SHA-release
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - run: npm ci
      - run: npx lerna bootstrap
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npx lerna bootstrap
      - run: npm run build

      - name: Deploy to npm
        run: npx lerna publish from-package --yes --registry https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Deploy to github packages
        run: npx lerna publish from-package --yes --registry https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_TOKEN}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  cleanup:
    needs: publish-npm
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Cleanup release branch
        run: git push -d origin $GITHUB_SHA-release
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
